/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dao;

import java.util.List;
import java.util.Vector;

import entity.Book;

public interface BookDao
{	

	/** 
	 * 插入一本书
	 */
	public int insert(Book book) ;

	/** 
	 * 修改一本书
	 */
	public int update(String isbn, Book book) ;

	/** 
	 * 删除一本书.
	 */
	public int delete(String isbn) ;

	/** 
	 * 根据主键isbn查找一本书.
	 */
	public Book findByPrimaryKey(String isbn) ;
	/** 
	 * Returns all rows from the books table that match the criteria 'and bookName = ? and publisherID = ?'.
	 */
	public List<Book> findByName_pID(String bookname,int publisherID) ;
	/** 
	 * Returns all rows from the books table that match the criteria 'and bookName = ? '.
	 */
	public List<Book> findByName(String bookname) ;
	/** 
	 * Returns all rows from the books table that match the criteria 'and publisherID = ?'.
	 */
	public List<Book> findByPID(int publisherID) ;

	/** 
	 * 查找所有书.
	 */
	public List<Book> findAll() ;
	/**
	 * 
	 * 
	 * @param sql
	 * @param sqlParams
	 * @return
	 */
	
	public List<Book> findByDynamicWhere(String sql, String[] sqlParams);
	/**
	 * 修改图书的库存量
	 * @param book
	 * @return
	 */

	public int updateCount( Book book) ;
	
}
