/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package dao;

import java.util.List;
import java.util.Vector;

import entity.User;




public interface UserDao
{	

	/** 
	 * Inserts a new row in the userdetail table.
	 */
	public int insert(User user);

	/** 
	 * Updates a single row in the userdetail table.
	 */
	public int update(String username, User user) ;
	/** 
	 * Updates a single row in the userdetail table.
	 */
	public int update_lognum(String username) ;	

	/** 
	 * Deletes a single row in the userdetail table.
	 */
	public int delete(String username, String userpass) ;

	/** 
	 * Returns all rows from the userdetail table that match the criteria 'and username = ?'.
	 */
	public User findByPrimaryKey(String username) ;
	/** 
	 * Returns all rows from the userdetail table that match the criteria 'and username = ? and userpass = ?'.
	 */
	public User findByName_pwd(String username,String userpass) ;

	/** 
	 * Returns all rows from the userdetail table that match the criteria ''.
	 */
	public List<User> findAll() ;
	
	public List<User> findByDynamicWhere(String sql, String[] sqlParams);
	
	public int regist(User user) ;
	



}
